jfd: Use `jj git push -c` instead of generating bookmark names

diff --git a/bin/jfd b/bin/jfd
--- a/bin/jfd
+++ b/bin/jfd
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-if ! repo_root=$(jj root); then
+if ! jj root >/dev/null; then
   echo >&2 "Failed to get repository root. Is this a jj repo?"
   exit 1
 fi
@@ -17,54 +17,50 @@ __________________________ /____/____________________________ /____/___
 JIFFYDIFFY
 echo >&2 "$JIFFYDIFFY"
 
-add-bookmark() {
-  local change=$1
-  local message=$(jj log -r "$change" --no-graph -T 'description.first_line()' | sed 's/\[[^]]*\]//g')
-  if ! name=$(ask-llm -q "Respond with a short (hyphen-separated, fewer than 12 characters) branch name based on this commit message: $message"); then
-    echo >&2 "ask-llm failed"
-    return 1
-  fi
-  local bookmark=$bookmark_prefix/$name
-  if ! jj bookmark create -r "$change" "$bookmark"; then
-    echo >&2 "Failed to create bookmark $bookmark at change $change"
-    return 1
-  fi
-  echo "$bookmark"
-}
-
 auto_track_pattern=$(jj config get remotes.origin.auto-track-bookmarks)
-if [[ $auto_track_pattern != *"/*" ]]; then
+if [[ $auto_track_pattern != *"/*" || $auto_track_pattern == *'"'* ]]; then
   echo >&2 "$0: Unsupported auto-track-bookmarks setting: $auto_track_pattern"
   exit 1
 fi
-bookmark_prefix=${auto_track_pattern%/\*}
+
+git_push_bookmark_template=$(jj config get templates.git_push_bookmark)
+if [[ $git_push_bookmark_template != '"'$auto_track_pattern ]]; then
+  # If auto-track-bookmarks is 'colin/*', the template must begin with '"colin/'
+  echo >&2 "$0: Unsupported git_push_bookmark template: $git_push_bookmark_template"
+  exit 1
+fi
 
 if ! changes=($(jj log -r stack --no-graph --reversed -T 'change_id ++ "\n"')); then
   echo >&2 "$0: Failed to list the current stack"
   exit 1
 fi
 
+# Push any changes that don't have auto-tracked bookmarks yet
+bookmarkless='stack ~ bookmarks("'"$auto_track_pattern"'")'
+if (( $(jj log -r "$bookmarkless" --count) )); then
+  if ! jj git push -c "$bookmarkless"; then
+    echo >&2 "$0: Failed to push changes without bookmarks"
+    exit 1
+  fi
+fi
+
 bookmarks=()
 for change in "${changes[@]}"; do
-  if ! change_bookmarks=($(jj log -r "$change" --no-graph -T 'local_bookmarks.map(|b| b.name())')); then
+  if ! change_bookmarks=($(jj log -r "$change" --no-graph -T 'local_bookmarks.map(|b| b.name() ++ "\n")')); then
     echo >&2 "$0: Failed to list bookmarks for change $change"
     exit 1
   fi
-  bookmark=
-  for cb in ${change_bookmarks[@]}; do
+  for cb in "${change_bookmarks[@]}"; do
     if [[ $cb == $auto_track_pattern ]]; then
-      bookmark=$cb
-      break
+      bookmarks+=("$cb")
     fi
   done
-  if [[ ! $bookmark ]]; then
-    if ! bookmark=$(add-bookmark "$change"); then
-      echo >&2 "$0: Failed to add a bookmark to change $change"
-      exit 1
-    fi
-  fi
-  bookmarks+=("$bookmark")
 done
+
+if (( ${#bookmarks[@]} != ${#changes[@]} )); then
+  echo >&2 "$0: Too many bookmarks; aborting"
+  exit 1
+fi
 
 for (( i = ${#bookmarks[@]} - 1; i >= 0; i-- )); do
   if ! gt untrack "${bookmarks[i]}" --force; then
