Finish implementing ssh-with-dotfiles
I've tested it with a very simple 'collect' script. I haven't tested an
'install' script yet.

diff --git a/bin/ssh-with-dotfiles b/bin/ssh-with-dotfiles
--- a/bin/ssh-with-dotfiles
+++ b/bin/ssh-with-dotfiles
@@ -15,7 +15,10 @@
 # ~/.$USER-ssh-home/.config/ssh-with-dotfiles/install exists, it is
 # executed. Finally, '$SHELL -li' is spawned.
 #
-# For help with SSH itself, run with no args (or see 'man ssh').
+# For help with SSH itself, run with no args or see 'man ssh'.
+set -u
+
+REAL_SSH=/usr/bin/ssh
 
 usage() {
   awk <"$0" -v script="$0" '/$^/{exit}; NR==2,0{gsub(/<SCRIPT>/, script); print substr($0, 3)}'
@@ -25,34 +28,66 @@ if [[ $1 == --help ]]; then
   usage
   exit
 elif [[ $# -eq 1 && $1 != -* ]]; then
-  collect_stdout=/dev/null
+  debug=
+  scripts_stdout=/dev/null
   hostname=$1
 elif [[ $# -eq 2 && $1 == --debug && $2 != -* ]]; then
-  collect_stdout=/dev/stderr
+  debug=yes
+  scripts_stdout=/dev/stderr
   hostname=$2
 else
-  exec -a ssh /usr/bin/ssh "$@"
+  exec -a ssh "$REAL_SSH" "$@"
 fi
 
-if ! tempdir=$(mktemp -d ssh-with-dotfiles.XXXX); then
-  echo >&2 "$0: Failed to create temp dir; continuing without dotfiles"
-  exec -a ssh /usr/bin/ssh "$hostname"
+if [[ ! -e ~/.config/ssh-with-dotfiles/collect ]]; then
+  echo >&2 "$0: ~/.config/ssh-with-dotfiles/collect doesn't exist; continuing without collecting dotfiles"
+  exec -a ssh "$REAL_SSH" "$hostname"
 fi
 
-if ! ~/.config/ssh-with-dotfiles/collect "$tempdir" >"$collect_stdout"; then
-  echo >&2 "$0: Failed to collect dotfiles; continuing without them"
-  exec -a ssh /usr/bin/ssh "$hostname"
+if ! tempdir=$(mktemp --tmpdir -d ssh-with-dotfiles.XXXX); then
+  echo >&2 "$0: Failed to create temp dir; aborting"
+  exit 1
 fi
 
-data=$(tar cf - -I 'zstd -15' "$tempdir" | base64 -)
+if [[ $debug ]]; then
+  printf >&2 "\e[35m%s: Collecting dotfiles into %s...\e[39m\n" "$0" "$tempdir"
+fi
+if ! ~/.config/ssh-with-dotfiles/collect "$tempdir" >"$scripts_stdout"; then
+  echo >&2 "$0: Failed to collect dotfiles; aborting"
+  exit 1
+fi
+
+if ! data=$(tar cf - -I 'zstd -15' -C "$tempdir" . | base64 -); then
+  echo >&2 "$0: Failed to tar and compress collected dotfiles; aborting"
+  exit 1
+fi
 
 quoted_home=~/.${USER@Q}-ssh-home
-exec -a ssh /usr/bin/ssh -t "$hostname" "
-  mkdir -p $quoted_home &&
-    export HOME=$quoted_home &&
-    base64 -d <<<'$data' | tar xf - -I zstd
-  if [[ -e ~/.config/ssh-with-dotfiles/install ]]; then
-    ~/.config/ssh-with-dotfiles/install
-  fi
-  exec \$SHELL -li
+if [[ $debug ]]; then
+  extract_message="printf >&2 '\e[36m%s remote: Extracting dotfiles...\e[39m\n' ${0@Q}"
+  tar_verbose_flag=v
+  shell_message="printf >&2 '\e[36m%s remote: Launching shell...\e[39m\n' ${0@Q}"
+else
+  extract_message=
+  tar_verbose_flag=
+  shell_message=
+fi
+remote_script="
+if ! mkdir -p $quoted_home; then
+  printf >&2 '%s remote: Failed to create %s\n' ${0@Q} $quoted_home
+  exit 5
+fi
+export HOME=$quoted_home
+if ! cd; then
+  printf >&2 '%s remote: Failed to cd into %s\n' ${0@Q} $quoted_home
+  exit 5
+fi
+$extract_message
+base64 -d <<<'$data' | tar x${tar_verbose_flag}f - --strip-components 1 -I zstd
+if [[ -e ~/.config/ssh-with-dotfiles/install ]]; then
+  ~/.config/ssh-with-dotfiles/install >$scripts_stdout
+fi
+$shell_message
+exec \$SHELL -i
 "
+exec -a ssh "$REAL_SSH" -t "$hostname" "bash -c ${remote_script@Q}"
