[pylon] ssh-with-dotfiles: pylon-specific changes

diff --git a/bin/ssh-with-dotfiles b/bin/ssh-with-dotfiles
--- a/bin/ssh-with-dotfiles
+++ b/bin/ssh-with-dotfiles
@@ -13,14 +13,15 @@
 # On the remote host, the collected dotfiles are placed in the directory
 # ~/.$USER-ssh-home. HOME is set to this path. If
 # ~/.$USER-ssh-home/.config/ssh-with-dotfiles/install exists, it is
-# executed. Finally, '$SHELL -li' is spawned.
+# sourced (not executed!) with the original homedir passed as the only
+# argument. Finally, '$SHELL -li' is spawned.
 #
 # For help with SSH itself, run with no args or see 'man ssh'.
 set -u
 
 REAL_SSH=/usr/bin/ssh
-COMPRESS='zstd -19'
-DECOMPRESS=zstd
+COMPRESS=gzip
+DECOMPRESS=gzip
 
 usage() {
   awk <"$0" -v script="$0" '/$^/{exit}; NR==2,0{gsub(/<SCRIPT>/, script); print substr($0, 3)}'
@@ -30,15 +31,18 @@ if [[ $# -gt 0 && $1 == --help ]]; then
   usage
   exit
 elif [[ $# -eq 1 && $1 != -* ]]; then
-  debug=
-  scripts_stdout=/dev/null
+  stdout=/dev/null
   hostname=$1
 elif [[ $# -eq 2 && $1 == --debug && $2 != -* ]]; then
-  debug=yes
-  scripts_stdout=/dev/stderr
+  stdout=/dev/stderr
   hostname=$2
 else
   exec -a ssh "$REAL_SSH" "$@"
+fi
+
+if "$REAL_SSH" -O check "$hostname" 2>/dev/null; then
+  echo >&2 "$0: ssh control socket exists; connecting directly..."
+  exec -a ssh "$REAL_SSH" "$hostname"
 fi
 
 if [[ ! -e ~/.config/ssh-with-dotfiles/collect ]]; then
@@ -54,10 +58,8 @@ if ! cd "$tempdir"; then
   echo >&2 "$0: Failed to cd to the temp dir; aborting"
 fi
 
-if [[ $debug ]]; then
-  printf >&2 "\e[35m%s: Collecting dotfiles into %s...\e[39m\n" "$0" "$tempdir"
-fi
-if ! ~/.config/ssh-with-dotfiles/collect "$tempdir" >"$scripts_stdout"; then
+printf >"$stdout" "\e[35m%s: Collecting dotfiles into %s...\e[39m\n" "$0" "$tempdir"
+if ! ~/.config/ssh-with-dotfiles/collect >"$stdout" "$tempdir"; then
   echo >&2 "$0: Failed to collect dotfiles; aborting"
   exit 1
 fi
@@ -67,32 +69,37 @@ if ! data=$(tar cf - -I "$COMPRESS" -C "$tempdir" . | base64 -); then
   exit 1
 fi
 
-quoted_home=\~/.${USER@Q}-ssh-home
-if [[ $debug ]]; then
-  extract_message_command="printf >&2 '\e[36m%s remote: Extracting dotfiles into %s...\e[39m\n' ${0@Q} \"\$(pwd)\""
-  shell_message_command="printf >&2 '\e[36m%s remote: Launching shell...\e[39m\n' ${0@Q}"
-  tar_verbose_flag=v
-else
-  extract_message_command=
-  shell_message_command=
-  tar_verbose_flag=
+if ! rm -rf "$tempdir"; then
+  echo >&2 "$0: warning: Failed to remove tempdir $tempdir"
 fi
-remote_script="
-if ! mkdir -p $quoted_home; then
-  printf >&2 '%s remote: Failed to create %s\n' ${0@Q} $quoted_home
+
+remote_script='
+new_home=$1
+decompress=$2
+if ! mkdir -p "$new_home"; then
+  printf >&2 "%s: Failed to create %s\n" "$0" "$new_home"
   exit 5
 fi
-if ! cd $quoted_home; then
-  printf >&2 '%s remote: Failed to cd into %s\n' ${0@Q} $quoted_home
+if ! cd "$new_home"; then
+  printf >&2 "%s: Failed to cd into %s\n" "$0" "$new_home"
   exit 5
 fi
-export HOME=$quoted_home
-$extract_message_command
-base64 -d <<<'$data' | tar x${tar_verbose_flag}f - --strip-components 1 -I ${DECOMPRESS@Q}
+orig_home=$HOME
+HOME=$new_home
+printf "\e[36m%s: Extracting dotfiles into %s...\e[39m\n" "$0" "$new_home"
+base64 -d - | tar xvf - --strip-components 1 -I "$decompress"
 if [[ -e ~/.config/ssh-with-dotfiles/install ]]; then
-  ~/.config/ssh-with-dotfiles/install >$scripts_stdout
+  if ! source ~/.config/ssh-with-dotfiles/install "$orig_home"; then
+    printf >&2 "%s remote: Install script failed\n" ${0@Q}
+    exit 6
+  fi
 fi
-$shell_message_command
-exec -l \$SHELL -i
-"
-exec -a ssh "$REAL_SSH" -t "$hostname" "bash -c ${remote_script@Q}"
+'
+printf >"$stdout" "\e[35m%s: Transferring dotfiles...\e[39m\n" "$0"
+if ! "$REAL_SSH" >"$stdout" -o ControlMaster=yes -o ControlPersist=2s -t "$hostname" "bash -c ${remote_script@Q} ssh-with-dotfiles-remote ~/.${USER@Q}-ssh-home ${DECOMPRESS@Q}" <<<"$data"; then
+  echo >&2 "$0: Failed to transfer dotfiles; aborting"
+  exit 1
+fi
+
+printf >"$stdout" "\e[35m%s: Execing ssh...\e[39m\n" "$0"
+exec -a "$0" "$REAL_SSH" "$hostname"
